# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-12-06 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Lecturer')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ind_jour', models.TextField(blank=True)),
                ('tot_ind_jour', models.IntegerField()),
                ('nind_jour', models.TextField(blank=True)),
                ('tot_nind_jour', models.IntegerField()),
                ('oth_pub', models.TextField(blank=True)),
                ('tot_oth_pub', models.IntegerField()),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Lecturer')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchGrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_grant', models.TextField(blank=True)),
                ('no_grant', models.IntegerField()),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Lecturer')),
            ],
        ),
        migrations.CreateModel(
            name='RIG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rig_name', models.CharField(max_length=200)),
                ('rig_sname', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='lecturer',
            name='rig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.RIG'),
        ),
    ]
