# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-12-06 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchgrant',
            name='rm_grant',
            field=models.IntegerField(default=32000),
            preserve_default=False,
        ),
    ]
